spring:
  datasource:
    url: jdbc:mysql://localhost:3306/virtual_cards
    # change these for your credentials
    username: youruser
    password: yourpassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.fasterxml.jackson: DEBUG

jwt:
  secret: someSuperLongAndRandomSecretKey123456789